과제 1-1
CodeSoom/react-week1-assignment-1 pull request #100
Opened 2021-05-07 12:05 UTC by studioLuda

2021-05-07 13:18 UTC, Kihyun92 requested changes
안녕하세요 :) 

커밋을 여러개로 쪼개주신게 좋네요!! 리뷰하기도 편한 것 같습니다 ㅎㅎ

코로나가 아니라니 다행입니다. 몸조리 잘 하시고, 빨리 회복되면 좋겠네요 ㅠㅠ

2021-05-07 13:18 UTC, Kihyun92 commented on src/index.js
> +const data = { count: 0 };
객체를 이용하여 문제를 해결해보셨군요! 좋습니다ㅎㅎ

하지만 const로 선언하여 객체로 값을 관리한다고 해서 재할당이 불가능한 것은 아니죠. 객체의 속성을 변경할 수 있으니까요. 이 경우에 이 속성은 언제 어디서 변하는지 예측하기 어려워집니다.

이번 과제의 의도를 조금 더 고민해보시면 좋을 것 같습니다 😊

2021-05-07 13:18 UTC, Kihyun92 commented on src/index.js
> +          }}
이 경우에는 핸들러 함수로 따로 만들어서 사용하는게 좋을 것 같네요! (아래 버튼도 마찬가지입니다.)

2021-05-07 13:18 UTC, Kihyun92 commented on src/index.js
> +        {[1, 2, 3].map((resetVal) => (
`resetVal`은 `resetValue`를 줄인걸까요?? 가능하면 줄이지 않고 사용하면 좋을 것 같아요. 다른 동료들은 val을 다른 방식으로 이해할 수 있을 것 같아요 😊

간단하게 value 나 number와 같이 명확하게 의도를 드러내주는게 좋을 것 같습니다~

2021-05-08 02:13 UTC, studioLuda commented on src/index.js
> +const data = { count: 0 };
코멘트 감사합니다! 

'왜  Let을 쓰지 않고 구현해야 하는지'
과제의 의도를 아직 잘 이해하지 못한 것 같아요!

제가 웹과 자바스크립트 공부가 많이 부족한 것 같습니다.

------ 앞으로의 계획 ------

1. 알려주신 키워드 = [ 값 관리,  재할당,  객체의 속성] 위주로 검색하고 공부 하겠습니다.
+ let, const 사용시 메모리상에서도 어떤 차이가 있는지도 찾아볼까 합니다. 


2. 과제 목표를 " let을 사용하지 않기"  --> "값 관리를 섬세하게 하기  : 재할당 제어(?) " 로 더 구체화 해서 접근해보겠습니다!


----- 공부  할점 & 의문점 ---
아직 조금 헷갈리는 점은, 재할당의 의미인것 같아요.

1-1 과제의 기능은 버튼을 클릭하면 버튼 텍스트 값이 변경되는 기능인데,
값의 변경 !== 재할당  인 것인가?! 하는 궁금증이 생깁니다.

더 공부하고 커밋드릴께요! 
리뷰 감사합니다~

2021-05-08 02:14 UTC, studioLuda commented on src/index.js
> +const data = { count: 0 };
혹시 제가 더 공부해야할 키워드 (놓친 키워드)가 있으면 알려주셔요~ 감사합니다!! :) 

> 객체를 이용하여 문제를 해결해보셨군요! 좋습니다ㅎㅎ
> 
> 하지만 const로 선언하여 객체로 값을 관리한다고 해서 재할당이 불가능한 것은 아니죠. 객체의 속성을 변경할 수 있으니까요. 이 경우에 이 속성은 언제 어디서 변하는지 예측하기 어려워집니다.
> 
> 이번 과제의 의도를 조금 더 고민해보시면 좋을 것 같습니다 😊

2021-05-08 02:16 UTC, studioLuda commented on src/index.js
> +          }}
> 이 경우에는 핸들러 함수로 따로 만들어서 사용하는게 좋을 것 같네요! (아래 버튼도 마찬가지입니다.)

네 수정하겠습니다. 

use-before-define << esLint에서 보고된 이 오류를 해결하는 다른 방법을 찾겠습니다!

2021-05-08 13:14 UTC, studioLuda commented on src/index.js
> +          {count}
/** [질문] count 대신에,
           count.count 로 접근하면 왜 undefined 가 되나요?

           render()의 파라미터 {count}는 객체인데,
           count 값에 접근하려면 객체.count 라고 해야 될 것 같은데
           바로 count로 접근이 가능한게 왜 그런지 잘 모르겠고 어렵게 느껴집니다 ㅠㅠ

           혼자 매번 javascript 공부할때마다 이런 부분에서 어려움을 느낍니다
           늘 기본이 부족하다고 느끼는데 어떻게 공부해야할지 막막하네요...
           여러 사용 방식에 대해서 정리된 책을 봐야할까요? ES6 문법을 일단 다 읽어보고 공부해야할까요? 어떻게 공부하면 좋을까요 ? */

2021-05-08 13:18 UTC, studioLuda commented on src/index.js
> + *    ==> 다른 분들의 코드나, 과제 해설을 보기 전까지는 render()안에 파라미터로 count를 넘겨줘서 해결할 수 있다는 생각을 하지 못했다 (ㅠㅠ)
저는 다른 분들이나 아샬님 처럼 
render()안에 파라미터로 count 를 넘겨 받아서 해결해야겠다고 생각을 하지 못했어요 ㅠㅠ

어떤 부분에 지식이 있어야 했는지,
혹은 어떻게  공부를 하고 또 생각을 해야 

이런 해결방법을 연결 지을 수 있었을지... 계속 고민이 됩니다. 
혹시 조언이나 추천해주실 공부방법, 책 이 있다면 도움 부탁드립니다!!

2021-05-08 13:25 UTC, studioLuda commented on src/index.js
> +          {count}
저는 프로그래밍 입문을 Java로 시작했는데,
내가 사용할 변수를 선언하고 , 인스턴스 생성하고 접근하는 방식에 많이 익숙합니다.
(자바 스크립트에 비해 규칙이 더 강하고 명확하다는 느낌을 받아요 )

그렇다보니 자바스크립트 공부를 시작하다보니
답이 있나? 란 생각이 들정도로 ^^; 
코드를 작성하는 방법이 너무 많다고 느껴서 혼란? 스러워요..

Javascript는 어떤 언어인가.. 상대적으로 익숙한 Java와는 어떤 점이 비슷하고 다른가 궁금증이 생겨요
(과제 해야하는데 자꾸 이런생각만 들고 ^^; ) 

멘토분들은 자바스크립트 공부를 처음 시작하셨을 때  
어떻게 공부하셨는지, 혹시 저와 비슷한 고민이 있으셨다면 어떻게 해결해 나가셨는지  조언 구합니다. :)

2021-05-08 13:49 UTC, Kihyun92 commented on src/index.js
> +          {count}
> count.count 로 접근하면 왜 undefined 가 되나요?

render 함수에 파라미터로 넘겨준 객체를 ES6 문법인 Destructuring(구조분해할당)을 통해서 객체를 풀어서 받아왔기 때문입니다. 만약 아래 예시와 같다면 말씀하신대로 객체에 접근해서 count 값을 받아와야 할겁니다.

```javascript
const render(count) {
  ...
  {count.count}
  ...
}

render({ count: 0 });
```
--- 

기존에 알던 기술과 무슨 점에서 다른지를 알아보는건 매우 좋은 것 같아요 ㅎㅎ 이해하는데도 더 도움이 될 것 같구요.

개인적으로도 혼자 공부하다가 취업 후에 많이 부딪혀보며 배웠던 것 같아요.

개개인마다 그리고 시기에 맞는 학습 스타일이 있을 것 같지만, 일단 이것저것 많이 시도해보시고 삽질을 해보는 것도 추천드립니다.

하다보면 자바스크립트의 단점들(강제성이 없다던지 등)을 극복하기 위해 타입스크립트를 사용하는 이유도 느끼실 수 있게 되실 거에요 :)

2021-05-08 13:52 UTC, Kihyun92 commented on src/index.js
> + *    ==> 다른 분들의 코드나, 과제 해설을 보기 전까지는 render()안에 파라미터로 count를 넘겨줘서 해결할 수 있다는 생각을 하지 못했다 (ㅠㅠ)
이 부분은 영상에서 아샬님도 말씀하시지만 경험을 해보는게 중요합니다 :)

이렇게 함으로써 객체나 배열을 통해 상태를 관리하는 것과 어떤 차이가 있는지 고민해보고 본인의 것으로 만들어야합니다.

이 부분은 함수형 프로그래밍, 순수 함수 관련해서 찾아보면 좋을 것 같습니다.

2021-05-08 14:01 UTC, Kihyun92 reviewed
학습한 내용을 주석으로 잘 정리해주신 것 같아요! 👍🏼 

주석 관련해서는 강제는 아니지만 동료들과 함께 관리하는 코드이기 때문에 가능하면 주석은 최소화하고, 커밋 메시지에 왜, 무엇을 위한 작업인지를 남기고, PR을 통해 본인의 의도나 생각을 더 자세히 적어주는게 좋을 것 같습니다 ㅎㅎ

특히 학습을 위한 주석이라면 더 사용하지 않고, 본인의 것으로 만드는게 좋을 것 같습니다. 주석에 의존하게 될 것 같아요.

2021-05-09 04:04 UTC, studioLuda commented on src/index.js
> +          {count}
사려깊은 조언과 설명 감사합니다! 

제 질문을 다시 읽어보니 글 쓸 당시 제가 너무 불안해 했나봅니다.
조언 주신대로 기본 돌아가는 방식 익숙해질 때 까지 삽질(?) 시간을 더 늘리고 ㅎㅎ
'구조분해할당' 같은 키워드 계속 공부해 나가겠습니다!!

오늘은 1-2 계산기 과제 일단 제 힘으로 다 끝내고
저녁이나 월요일 오전에 피드백 반영 &  키워드 공부 진행하겠습니다.
감사합니다!!

2021-05-09 04:06 UTC, studioLuda commented on src/index.js
> + *    ==> 다른 분들의 코드나, 과제 해설을 보기 전까지는 render()안에 파라미터로 count를 넘겨줘서 해결할 수 있다는 생각을 하지 못했다 (ㅠㅠ)
넵!! 화이팅!!

------ 공부할 키워드 리스트

* 함수형 프로그래밍
* 순수 함수
* 구조분해할당

2021-05-09 04:15 UTC, studioLuda commented
사려깊은 조언과 설명 감사합니다!

조언 주신대로 기본 돌아가는 방식 익숙해질 때 까지 삽질(?) 시간을 더 늘리고 ㅎㅎ
알려주신 키워드들 계속 공부해 나가겠습니다!!

오늘은 1-2 계산기 과제 일단 제 힘으로 다 끝내고
알려주신 키워드 공부 진행하겠습니다! :)

------ 공부할 키워드 리스트------

* 함수형 프로그래밍
* 순수 함수
* 구조분해할당

2021-05-09 13:22 UTC, Kihyun92 commented
[린트 에러](https://github.com/CodeSoom/react-week1-assignment-1/pull/100/checks?check_run_id=2538617171)가 있는 것 같아요. 항상 푸시 전에 확인 부탁드립니다~ 

그리고 모던 자바스크립트 문법을 공부하시려면 자바스크립트 코딩의 기술 책도 추천드려요~ :)

2021-05-09 16:21 UTC, studioLuda commented
>

2021-05-09 16:23 UTC, studioLuda commented
린트 오류 수정하였습니다 ! 
다음부터는 확실히 검사하겠습니다!
'자바스크립트 코딩의 기술'도 얼른 읽겠습니다 :) 감사합니다!

2021-05-10 12:45 UTC, studioLuda commented
제가 실수로 PR을 닫았습니다 확인 부탁드려요!

2021-05-10 13:58 UTC, Kihyun92 commented
수정 확인했습니다~ 과제 머지하도록 하겠습니다 :)

회고도 잘 읽었습니다. 리뷰가 도움이 된 것 같아 저도 힘이 나네요! 🙏🏻

2021-05-10 14:00 UTC, merged