refactor : let 제거로 변수 재할당 제거
CodeSoom/react-week1-assignment-1 pull request #55
Opened 2021-01-18 12:30 UTC by shinhyogeun

안녕하세요! 트레이너님!!😳
처음 리뷰요청을 보내봅니다!

제가 한 것은 let을 제거하기 위해 const 변수 = 리터럴객체를 이용해보았습니다! (react의 state가 생각이 나서..하하..)

하지만 eslint검사에서 2개 오류가 났습니다.ㅠㅠ 
함수가 선언전에 사용해야한다는 규칙이 있는데 render()와 handleClick()이 서로를 안에서 사용해서 이 규칙을 지키기 힘듭니다..

(또한 지금 깃까지 Can’t automatically merge 경고가 뜨지만 PR은 보낼 수 있다고 해서 일단은 리뷰를 받기 위해 PR를 보내볼게요! 
감사합니다!

2021-01-18 13:27 UTC, Kihyun92 commented on src/index.js
> +};
let을 피하기 위해서 const를 사용해보신 것 같아요~
하지만 여전히 객체의 속성은 재할당 가능합니다.

이 방법보다는 뭔가 `immutable`하게 상태값을 관리할 수 있는 방법이 있을 것 같습니다! 조금 더 고민해보시면 좋을 것 같아요~

2021-01-18 14:29 UTC, shinhyogeun commented on src/index.js
> +};
리뷰 감사합니다! 더 고민해서 다시 올려보도록 할게요!

2021-01-18 15:01 UTC, Kihyun92 requested changes

2021-01-18 15:09 UTC, shinhyogeun commented on src/index.js
> +function render(count) {
default value를 사용하겠습니다!! 
깃을 주말에 연습하다고 했는데 아직은 살짝 헷갈려서요.. 🥲
"This branch has conflicts that must be resolved" 이라고 나오고 
Conflicting files에 src/index.js이 나오는데 혹시 이게 제가 rebase를 했어야 했는데 안해서 그런건가요??

2021-01-19 13:13 UTC, Kihyun92 approved these changes
리뷰를 잘 반영해 주신 것 같아요~ 👍🏼 

처음 코드랑 비교했을때 어떤 점이 달라졌나요?

2021-01-19 13:21 UTC, shinhyogeun commented
> 리뷰를 잘 반영해 주신 것 같아요~ 👍🏼
> 
> 처음 코드랑 비교했을때 어떤 점이 달라졌나요?

2021-01-19 13:24 UTC, shinhyogeun commented
좀 더 함수 하나안에서 단단해진 느낌이라고 해야할까요.. 
 처음에는 let count가 소속된 곳 없이 떠돌아다니는 느낌이었는데 지금은 재귀를 이용해서 더 체계적인 느낌이 나네요!👍

2021-01-24 14:16 UTC, merged