Remove let
CodeSoom/react-week1-assignment-1 pull request #57
Opened 2021-01-18 12:49 UTC by dodoongtak

해결방법 : 
let을  안 사용하기위해 object를 활용했습니다. 

풀지 못한 점 : 
Eslint issues : no-use-before-define, jsx-expression per one line, jsx-filename-extension 

질문 : 
jsx-filename-extension은 트레이너님께서 index.js 에서 disable을 추가하셨는데 eslint에서 아직 걸러지지 못한거같은데 제가 잘못파악한건가요?

2021-01-18 14:36 UTC, Kihyun92 requested changes
적극적으로 문제를 해결하시는 모습이 보기 좋습니다 😁

과제의 의도를 잘 파악하신 것 같아요~

2021-01-18 14:36 UTC, Kihyun92 commented on src/index.js
> +render(0);
render 함수에 default value가 있기 때문에 굳이 없어도 될 것 같네요~
```suggestion
render();
```

2021-01-18 14:36 UTC, Kihyun92 commented on src/index.js
> +  const { presentNumber } = count;
let 대신에 const를 사용하여 counter변수는 재할당할 수 없게 해주셨네요 ㅎㅎ 하지만 객체의 속성은 여전히 재할당이 가능합니다.

이미 답을 찾으신 것 같은데, 불필요한 코드는 없는지, 조금 더 고민해보시면 좋겠어요 👍🏼

2021-01-18 14:44 UTC, dodoongtak commented on src/index.js
> +  const { presentNumber } = count;
아 이번 문제 목적이 let을 사용을 자제하라해서 const를 사용했구요. 

아래 코드에서 count.presentNumber를 사용하기보다 presentNumber로 사용 할 목적으로 destructuring했습니다. 

과한 destructuring은 피해야 될까요?

2021-01-18 14:45 UTC, dodoongtak commented on src/index.js
> +render(0);
넵 반영하겠습니다! 불필요한 코드는 최대한 제거... noted...

감사합니다 :)

2021-01-18 14:55 UTC, Kihyun92 commented on src/index.js
> +  const { presentNumber } = count;
아앗 ㅎㅎ 이번 과제의 의도는 단순히 let을 사용하지 않기 위해 const를 사용해보는게 아닙니다.

`immutable`한 코드를 만들어보는게 과제의 의도입니다. 현재 render함수는 매개변수에 의해서만 동작하도록 잘 작성해주셨어요.

그런데 굳이 count라는 변수에 할당을 해야할까요?ㅎㅎ `presentNumber`가 결국 어떤 값인가요?

2021-01-18 15:27 UTC, dodoongtak commented on src/index.js
> +  const { presentNumber } = count;
아하! 제가 다른 방향으로 빠졌었네요. 퓨어하게... 만들라는게 의도인데! 굳이 presentNumber 혹은 count가 필요없이도 구현 가능 할 수 있겠어요! 

리뷰 감사합니다 :)

2021-01-19 13:36 UTC, Kihyun92 approved these changes
리뷰를 잘 반영해 주신 것 같아요~ :)
처음 코드랑 비교했을때 어떤 점이 달라졌나요? 고민해보시면 좋겠습니다.

추가로 immutable과 순수 함수 관련해서 괜찮은 글을 아직 찾지 못했네요 ㅎㅎ.. 
조금 어려울 수 있지만, [순수 함수 더 나아가 함수형 프로그래밍에 대한 문서](https://medium.com/@jooyunghan/%ED%95%A8%EC%88%98%ED%98%95-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D%EC%9D%B4%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%B8%EA%B0%80-fab4e960d263)입니다.

다른 괜찮은 문서들 찾으면 채널에 공유 해보겠습니다~

2021-01-20 11:15 UTC, dodoongtak commented
비교 : 

초기 코드
- 외부에 선언된 변수가 조작됨에 따라 특정 출력을 목표로하는 함수가 훼손 가능성이 농후.

수정 코드 
- 어떠한 입력을 받아도 함수에 있는 로직 그대로 출력이 되어 변수 생기지 않게 방지.

미션의 목표 : 
- 각기 다른 외부 변수에 의존성을 낮추고 함수의 특정 로직이 언제나 그대로 반영 헤야함.

미션 후 다짐 : 
- immutable 혹은 pure하게 완성도 높은 함수를 단번에 작성 할 수는 없지만, 
주의하며 최대한 변동성이 없는 함수를 작성 하는 습관 들이기

2021-01-24 14:16 UTC, merged