Remove let
CodeSoom/react-week1-assignment-1 pull request #62
Opened 2021-01-19 05:48 UTC by datalater

1주차 1번 과제 제출합니다!!!!!

과제 해결 방법
1. let을 쓰지 않고 값을 재할당하기 위해 상수 객체를 사용했습니다.
2. eslint no-use-before-define을 피하기 위해 handler 함수를 render 함수 안에 넣었습니다.

궁금한 점
1. render 함수가 호출될 때마다 handler 함수 선언을 반복하게 되는데 이러면 메모리 낭비가 있지 않나요?
2. 첨부된 이미지를 보면, eslint disable 항목을 한 개 더 추가해야 이 미션을 통과할 수 있다고 했는데 전혀 감이 잡히지 않습니다. 어떻게 접근해야 할까요?

![image](https://user-images.githubusercontent.com/8105528/104992878-43c34700-5a65-11eb-92fb-20a75794dfc4.png)

2021-01-19 05:54 UTC, datalater commented
commit 이름을 아래와 같이 변경했습니다.

from: `Refactor to avoid eslint no use before define rule`
to: `Refactor to pass eslint no use before define rule`

이유: 규칙을 피하는 것보다 통과한다는 말이 더 어울린다.

2021-01-19 16:32 UTC, moonkii requested changes
과제 해결을 잘 해나가고 있으신 것 같아요.
몇가지만 보완하시면 더 좋은 결과를 얻을 수 있을 것 같네요 :) 

PR 타겟 브랜치는 `CodeSoom:datalater` 로 변경해주세요!

---

> render 함수가 호출될 때마다 handler 함수 선언을 반복하게 되는데 이러면 메모리 낭비가 있지 않나요?

함수 선언을 위한 메모리 할당은 신경쓸 정도는 아닌 것 같아요. 오히려 코드가 보여주려는 의도가 더 중요하다고 생각해요. 
메모리 낭비가 신경쓰인다면 이벤트 핸들러에서 함수를 직접 호출하는 방식 보다 내부에서 함수로 만들어 넘겨주는 방식을 사용하면 메모리 낭비를 조금은 줄일 수는 있을 것 같네요 ;) 이벤트 핸들러에서 함수를 직접 호출하면 매번 `render()` 마다 새로운 메모리에 함수가 생성되기 때문이죠.

> 첨부된 이미지를 보면, eslint disable 항목을 한 개 더 추가해야 이 미션을 통과할 수 있다고 했는데 전혀 감이 잡히지 않습니다. 어떻게 접근해야 할까요?

`eslint` 에 이상이 없으면 이 부분은 과제 풀이 영상 아래에 있는 설명을 참고 정도만 하시면 좋을 것 같아요.

2021-01-20 04:23 UTC, datalater commented
> PR 타겟 브랜치는 `CodeSoom:datalater` 로 변경해주세요!

넵 변경했습니다. 어떤 식으로 풀리퀘가 이뤄지는지 이제 이해했네요 😄 

> 메모리 낭비가 신경쓰인다면 이벤트 핸들러에서 함수를 직접 호출하는 방식 보다 내부에서 함수로 만들어 넘겨주는 방식을 사용하면 메모리 낭비를 조금은 줄일 수는 있을 것 같네요 ;) 이벤트 핸들러에서 함수를 직접 호출하면 매번 `render()` 마다 새로운 메모리에 함수가 생성되기 때문이죠.

음.. 잘 이해가 안되는데요😢 혹시 코드로 설명해주실 수 있나요?

> `eslint` 에 이상이 없으면 이 부분은 과제 풀이 영상 아래에 있는 설명을 참고 정도만 하시면 좋을 것 같아요.

과제 풀이 영상은 나중에 올라오는 거죠?

2021-01-20 04:25 UTC, datalater commented on src/index.js
> +};
> 단순히 let 을 대체하는게 아니라 외부 변수에 의존하는 상태를 없애 immutable 하게 관리할 수 있도록 고민을 더 해보시면 좋을 것 같아요.

render 함수가 자신의 스코프 안에서 값을 관리해야 한다는 말인가요?

2021-01-20 04:28 UTC, datalater commented on src/index.js
> +  }
엌 실수입니다...ㅋㅋㅋㅋ handleClick에서 매개변수 사용하지 않는 것으로 고쳐서 올리겠습니다.

2021-01-20 04:30 UTC, datalater commented on src/index.js
> +
넵 지우겠습니다!

2021-01-20 04:39 UTC, datalater commented on src/index.js
> +  }
`eb2cdac

2021-01-20 04:40 UTC, datalater commented on src/index.js
> +
`eb2cdac`

2021-01-20 16:24 UTC, moonkii commented on src/index.js
> +};
지금 상태에서 외부 변수를 지워보고 코드가 작동하도록 고민해보세요

2021-01-20 16:39 UTC, moonkii commented
> 음.. 잘 이해가 안되는데요😢 혹시 코드로 설명해주실 수 있나요?

중요한 부분은 아니라서 지금 과제에 더 집중하시면 좋을 것 같아요.
질문하셔서 간단하게 설명 드리면

` <button type="button" onClick={() => handleClick()}>`  은 이벤트 핸들러에서 함수를 직접 호출하는 방식이고

` <button type="button" onClick={handleClick}>`  은 이벤트 핸들러에 함수를 넘겨주는 방식이에요.

> 과제 풀이 영상은 나중에 올라오는 거죠?

네 과제 풀이 영상은 일요일에 올라올거에요.

2021-01-21 02:26 UTC, datalater commented
> `<button type="button" onClick={() => handleClick()}>` 은 이벤트 핸들러에서 함수를 직접 호출하는 방식이고
> 
> ` <button type="button" onClick={handleClick}>` 은 이벤트 핸들러에 함수를 넘겨주는 방식이에요.

그렇군요. 이해됐습니다. 정말 감사합니다!

2021-01-21 02:40 UTC, datalater commented on src/index.js
> +};
변수 count 인자로 사용하도록 하고 count의 값이 함수 내에서 변경되지 않도록 했습니다.

5515317

2021-01-21 04:15 UTC, moonkii commented
> 그럼 만약에 이벤트 핸들러에 함수를 넘겨줄 때 인자(예를 들어, id)도 함께 넘기고 싶으면
> 
> ` <button type="button" onClick={handleClick(id)}>`
> 
> 위와 같이 하나요? 저렇게 되면 함수를 직접 호출하게 되는 것 같아서 궁금해서 질문드립니다🤔

인자를 직접 넘겨주고 싶으면 함수를 호출하는 방식으로 사용해야 해요.

그렇게 하고 싶지 않으면 해당 인자를 다른곳에서 넘겨주는 식으로 구조를 바꾸든지 해야겠죠?

기존에 `handleClick(id)` 였지만 `render` 함수에 인자를 넘겨주는 방식으로 변경하고나선 그럴 필요가 없어진 것과 똑같아요.

2021-01-21 04:16 UTC, moonkii commented on src/index.js
> +  function handleClick() {
이 함수는 어떤 역할을 하는 걸까요?

이름에서 의도가 더 드러나도록하면 좋을 것 같아요.

`handleClickNumber` 와 비교해보시면 좋겠네요 :)

2021-01-22 08:57 UTC, datalater commented on src/index.js
> +  function handleClick() {
와 어렵네요.

`handleClickNumber`와 비교했을 때:

* `handleClickNumber`:`넘버` 버튼을 클릭하는 것을 핸들링한다 
* `handleClick___`:`___`버튼을 클릭하는 것을 핸들링한다

위와 같이 유추해서 `handleClickMe`라고 고쳤습니다만, 여전히 ClickMe 버튼을 뭐라고 지칭해야 할지 잘 모르겠네요...
... 이게 맞을까요?😢

2021-01-22 08:57 UTC, datalater commented on src/index.js
> +  function handleClick() {
d83008c

2021-01-22 15:59 UTC, moonkii commented on src/index.js
> +  function handleClick() {
누군가에게 한국어로 설명한다고 생각해보시면 조금 더 쉬울거에요.

이걸 클릭하면 숫자가 올라갈거야, 숫자를 세는거야 등등이 있겠죠?

그리고 `render` 에서 `count` 라고 받고 있는걸 감안하면  `handleClickCount` 정도가 될 수 있을 것 같네요 ;)

2021-01-22 16:00 UTC, moonkii approved these changes
과제의 의도를 잘 파악하여 과제를 해결하셨어요! 👏 👏 👏 

이번 주 공부한 것과 과제한 것들을 복습차원에서 회고 글을 작성해 보시고  슬랙 주간회고에 공유해주세요!

주간회고에 회고 올리시는 대로 PR은 머지하도록 하겠습니다 :)

2021-01-23 03:15 UTC, datalater commented on src/index.js
> +  function handleClick() {
034a4af

2021-01-23 03:15 UTC, datalater commented
리뷰해주셔서 감사합니다! 회고로 정리해서 올리겠습니다.

2021-01-24 11:00 UTC, datalater commented
주간회고를 남겼습니다.

https://www.notion.so/jayday/1-439be1ceb71248f6a3daad33a48fd759

2021-01-24 15:20 UTC, merged