let 을 제거하는 과제
CodeSoom/react-week1-assignment-1 pull request #63
Opened 2021-01-19 06:01 UTC by gyeongwon1275

react/jsx-one-expression-per-line 를 제외하고 eslint rule 을 지키면서 코드를 작성했습니다. 

eslint 의 no-use-before-define 을 지키기 위해 객체 안에 state, methods 를 선언했습니다.

2021-01-19 16:55 UTC, moonkii requested changes
![Screenshot](https://user-images.githubusercontent.com/46776329/105066206-06d96d80-5ac2-11eb-91ec-69038c8cc8a9.png)

객체로 문제를 해결 하려고 한 발상은 좋았던 것 같아요!

하지만 `let` 을 제거하는 의도에 대해 더 고민해보시면 좋을 것 같아요.

> eslint 의 no-use-before-define 을 지키기 위해 객체 안에 state, methods 를 선언했습니다.

객체 안에서 모든걸 선언하고 문제를 해결하려다 보니 코드가 복잡하고 가독성이 떨어지는 것 같아요.
객체 안에서 선언하는 것 외에 더 간단히 문제를 해결할 수 있는 방법은 없을까요??

2021-01-19 16:55 UTC, moonkii commented on src/index.js
> +    },
화면을 그리는 `render` 부분을 포함하여 여러 함수들을 Object 내부에 선언하여 관리하는 것과 function 으로 따로 분리하여 관리하는 것 중 어느쪽이 더 나은 것 같은가요?

왜 하나의 Object 로 모든 요소를 관리하려고 했는지 고민해보시면 좋을 것 같아요.

2021-01-19 16:55 UTC, moonkii commented on src/index.js
> +countChange.methods.render();
`countChange` 가 왜 `methods` 를 가지고 있고 `render()` 를 가지고 있는지 의도를 파악하기가 어려운 것 같아요.

`countChange` 는 어떤 역할을 하는 객체일까요?

화면을 그리는 걸 관리하는 역할일까요 아니면 상태를 관리하는 역할일까요? 

코드만으로 의도가 드러날 수 있도록 작성하는게 중요해요.

2021-01-19 16:55 UTC, moonkii commented on src/index.js
> +    count: 0,
객체는 `const` 로 선언해도 속성을 변경할 수 있는 점을 이용해서 문제를 해결하려고 하신 점은 좋은 시도 같아요 :)

다만 `let` 을 제거 한다는 것은 단순히 `let` 을 제거한다기 보다 외부 변수에 의존하여 수정하는 구조를 끊어내려고 하는 의도에 가까워요.

어떻게하면 외부 변수 없이 직접 상태를 바꿀 수 있을까 고민해보시면 좋을 것 같아요!

2021-01-19 16:55 UTC, moonkii commented on src/index.js
> +  },
`setState` 만 보았을 때에는 상태를 관리해주는 함수로 추측이 되는데 왜  화면을 그리는 `render()` 까지 포함되어 있을까요?

하나의 함수는 하나의 역할만 하는 단일 책임원칙을 준수하는게 좋아요.

하나의 함수가 두 가지 이상의 역할을 하고 있다면 함수를 쪼개거나 구조를 변경해야하는 신호로 받아들이시면 좋을 것 같네요 ;)

2021-01-20 01:18 UTC, gyeongwon1275 commented on src/index.js
> +    },
let 을 사용하지 않으면서 no-use-before-define 을 회피하는 데 정신이 사로잡혀서 
개별함수 역할이나 가독성 생각하지 않고 객체하나에 다 때려넣어버렸네요.. 
외부변수에 의존하지 않는다는 걸 생각해서 함수자체 argument 로만 상태변화를 주는 것으로 수정했습니다!

2021-01-20 17:04 UTC, moonkii commented on src/index.js
> +render(0);
호출 할 때 `0` 을 넣어서 초기화 해줄수도 있지만 매개변수에 default 값을 넣어 줄 수도 있어요.

처음에 값을 `0` 을 주는 것과 default 값을 주는 것 중 어느것이 더 의도가 잘 드러난다고 생각하시나요?

2021-01-20 17:06 UTC, moonkii commented on src/index.js
>    function handleClick() {
이 함수는 어떤 역할을 하는 함수일까요?

변수나 함수명에 의도가 잘 드러나도록 고민해보면 좋을 것 같아요.

2021-01-20 17:07 UTC, moonkii commented on src/index.js
> +    };
로직을 더 단순하게 할 순 없을까요?? 

단순히 클릭한 숫자가 보이는 로직인데 왜 `currentCount` 와 `nextCount` 2개나 필요할까요?

2021-01-21 04:10 UTC, moonkii commented on src/index.js
> +    return render(nextCount);
매개변수이름이 nextCount 라고 되어있으면 코드를 읽을 때 무슨 생각을 하게 될까요?

코드를 봤을 때 의도는 단순히 숫자를 눌렀을 때 해당 숫자를 보여주도록 랜더링하는 것으로 보여요.

코드 가독성을 생각할 때는 누군가 내 코드를 읽을 때 추측할 필요가 없도록 하는게 중요해요!

저도 그래서 프로그래밍할 때 오히려 변수명, 함수명을 고민하는데 시간을 제일 많이 쓰는 편이에요.

2021-01-21 15:32 UTC, moonkii commented on src/index.js
> +    return render(numberToChange);
단순하게 `number` 정도만 넣어주더라도 충분할 것 같아요!

2021-01-24 13:20 UTC, moonkii approved these changes
문제의 의도에 맞춰 잘 해결하셨어요 👏 👏 👏 

공유해주신 회고도 잘 읽었어요. 고민의 방향이 좋은 것 같아요 :)

PR 머지하겠습니다!

2021-01-24 13:20 UTC, merged