Remove let
CodeSoom/react-week1-assignment-1 pull request #65
Opened 2021-01-19 12:25 UTC by canary4651

Remove `let` and use `const`.

To do
1.  변수에 값을 재할당 하지 않고 문제를 해결
2. 문제 없이 통과시키려면 총 3개의 disable 항목이 필요

2021-01-19 17:07 UTC, moonkii requested changes
![Screenshot](https://user-images.githubusercontent.com/46776329/105068253-13f75c00-5ac4-11eb-9dfd-756dc3811daf.png)

외부 변수없이 값을 전달할 수 있는 방법은 무엇이 있을까요?

2021-01-19 17:07 UTC, moonkii commented on src/index.js
> +const count = { number: 0 };
객체는 `const` 로 선언해도 내부 속성의 값이 변경 가능하다는 점을 이용하여 문제를 해결하려고 시도 하신 점은 잘하셨어요!

다만 `let` 을 없앤다는 건 외부 변수에 의존하지 않고 상태를 변경할 수는 없는지에 대해 더 고민해보시면 좋을 것 같아요 :)

2021-01-20 13:08 UTC, canary4651 commented on src/index.js
> +const count = { number: 0 };
let을 업앤다는 건 외부 변수에 의존하지 않고 상태를 변경할 수 없는지...! 
외부 변수에 의존하지 않고 상태를 변경하게끔 만들어야 하군요. 더 고민해볼게요 ㅎㅎ

2021-01-20 15:31 UTC, canary4651 commented on src/index.js
> +const count = { number: 0 };
이번 과제에 핵심은  단순히 let을 const로 바꾸는 게 아니라 순수한 함수를 만들어야 한다에 중점을 두는 걸까요?

```js
let count = 0;

const handleClick = () => { count + 1 }
````
handleClick() 할 때마다 +1씩 증가 -> count의 상태도 1씩 증가
외부에 있는 count로 인해 상태가 계속해서 변경됨 

```js
const handleClcik = (a) => { a + 1 }

const a = 0;
```
handleClick이 a를 인자로 받고 그 안에서 +1 씩 증가 
a는 계속 변하지 않는 0 값

로 이해해봤는 데 고민의 방향이 맞는 지 궁금합니다. ㅎㅎ

2021-01-20 17:11 UTC, moonkii commented on src/index.js
> +  const handleClick = () => {
이 함수는 어떤 역할을 하는 함수 일까요?

`handleClickNumber` 처럼 이름에서 의도가 더 드러나면 좋을 것 같아요.

2021-01-20 17:12 UTC, moonkii commented on src/index.js
> +const count = { number: 0 };
방향성을 잘 잡으신 것 같아요.  👏👏👏

열심히 고민한 흔적이 보이는 것 같아서 좋네요 :)

2021-01-21 01:25 UTC, canary4651 commented on src/index.js
> +  const handleClick = () => {
버튼을 클릭할 때마다 숫자를 증가시키는 함수라고 생각되는 데, 
그렇다면 `handleClcikPlus` 이런 이름이 더 의도가 드러나는 걸까요?

2021-01-21 04:01 UTC, moonkii commented on src/index.js
> +  const handleClick = () => {
> 버튼을 클릭할 때마다 숫자를 증가시키는 함수라고 생각되는 데,

이게 함수의 역할이겠죠? 그러면 숫자를 증가시키는 걸 드러내주면 좋을 것 같아요

2021-01-21 14:55 UTC, canary4651 commented on src/index.js
> +  const handleClick = () => {
숫자를 증가시키는 거에 의미가 있다면 `handleClickPlusNumber` 로 작성하면 의미가 더 드러날 거 같아요. 
그렇게 고치겠습니다.

2021-01-21 16:12 UTC, moonkii approved these changes
과제를 잘 해결하셨어요!  👏👏👏 

과제 하신거나 공부하신 것들 회고해서 슬랙에 주간 회고 올려주시면 PR 머지 될거에요!

2021-01-24 14:55 UTC, merged