count 구현
CodeSoom/react-week1-assignment-1 pull request #72
Opened 2021-01-19 18:02 UTC by hxunz

- handleClick을 통해 버튼누를때마다 카운트 숫자가 올라감
- handleClickNumber을 통해 Click me!옆 카운트 숫자가 아래에 배치된 숫자와동일하게 초기화되도록 구현

우선 강의대로 한 것을 토대로 pr해봤습니다.
과제는 아직 진행중입니다..

2021-01-20 13:42 UTC, Kihyun92 commented
일단 PR을 올려주신 점이 매우 좋네요~ 다음 작업 기다리고 있겠습니다~ㅎㅎ

2021-01-21 13:50 UTC, Kihyun92 commented
혹시 진행이 어떻게 되고 있을까요~ 어려운 점이 있다면 공유해주시면 좋을 것 같아요☺️

2021-01-22 11:33 UTC, hxunz reviewed
오류가 생긴것은 인지를 하였으나 그 이유를 찾지 못해서 ,, 우선 코드 먼저 올립니다..

2021-01-22 13:43 UTC, kimkhyun requested changes
> 오류가 생긴것은 인지를 하였으나 그 이유를 찾지 못해서 ,, 우선 코드 먼저 올립니다..

인지한 오류가 어떤걸까요? 에러 화면을 캡쳐해주시면 더 리뷰하기 좋을 것 같아요!

2021-01-22 13:43 UTC, kimkhyun commented on src/index.js
> +  const count = { value: 0 };
let 을 사용하지 않기위해 const와 객체를 활용해서 문제를 해결해보려 하신것 같아요~ ☺️

틀린 방법은 아니지만, 이번 과제에서 let을 사용하지 말라고 한 이유에 대해서 한번 고민해보시면 좋겠습니다.

const로 선언한 객체는 직접 재할당 할 수 없지만, 여전히 객체의 속성에는 값이 재할당되고 있습니다. 이러면 이 속성은 언제 어디서 변하는지 예측하기 어렵겠죠.
또한 render 함수에서는 함수 바깥의 변수에 접근하다보니 테스트가 어려워지고 마찬가지로 코드가 어떻게 동작할지 예측하기 힘들어집니다. render함수가 내부의 변수로만 동작한다면 어떨까요? ☺️

2021-01-22 13:45 UTC, Kihyun92 commented on src/index.js
> +  const count = { value: 0 };
let 을 사용하지 않기위해 const와 객체를 활용해서 문제를 해결해보려 하신것 같아요~ ☺️

틀린 방법은 아니지만, 이번 과제에서 let을 사용하지 말라고 한 이유에 대해서 한번 고민해보시면 좋겠습니다.

const로 선언한 객체는 직접 재할당 할 수 없지만, 여전히 객체의 속성에는 값이 재할당되고 있습니다. 이러면 이 속성은 언제 어디서 변하는지 예측하기 어렵겠죠.
또한 render 함수에서는 함수 바깥의 변수에 접근하다보니 테스트가 어려워지고 마찬가지로 코드가 어떻게 동작할지 예측하기 힘들어집니다. render함수가 내부의 변수로만 동작한다면 어떨까요? ☺️

2021-01-22 15:46 UTC, hxunz reviewed
render 내부에 혹시 오류가 있을까요? 클릭버튼을 눌러도 변화가 없네요,,
콘솔을 보니 이러한 에러가 떴는데 혹시 이것과 연관이 있는걸까요?
<img width="797" alt="스크린샷 2021-01-23 오전 12 46 33" src="https://user-images.githubusercontent.com/77002038/105512442-73e44180-5d14-11eb-8db5-7062f742cb86.png">

2021-01-23 13:33 UTC, Kihyun92 approved these changes
좋습니다. 이번 과제의 의도에 맞게 처리해주셨네요 

처음 코드와 비교했을때 어떻게 달라졌나요? ㅎㅎ 과제 풀이 영상은 꼭 보시면 좋겠어요!

2021-01-24 14:01 UTC, Kihyun92 commented
회고 올려주시면 머지하겠습니다~

2021-01-31 08:39 UTC, merged