Change var to const with regex
CodeSoom/react-week1-assignment-1 pull request #78
Opened 2021-01-20 14:41 UTC by minseongkimdev

안녕하세요 트레이너님~ 항상 수고가 많으십니다!

제가 eslint-disable 옵션을 추가하지 않고 정규식과 const를 이용해서 과제를 완료 하였는데, 

혹시 제가 과제를 정확하게 이해한것인지 잘 모르겠습니다.

아낌 없는 피드백 기대하겠습니다!!

2021-01-21 14:14 UTC, Kihyun92 requested changes

2021-01-21 14:14 UTC, Kihyun92 commented on src/index.js
> +// eslint config에 직접 추가하는게 아니라 index.js 상단에 추가하는것이 좋다. 프로젝트 전역에 규칙이 적용되기 때문이다.
주석으로 시작해서 기능을 구현하는 방식은 저는 좋다고 생각합니다 ㅎㅎ 다만, PR을 올리기 전에 불필요한 주석은 제거해주세요~

이런저런 설명을 적은 주석 없이도 동료, 혹은 미래의 내가 코드만 보고도 이해될 수 있도록 작성하는 연습을 해보는게 좋습니다 :)

2021-01-21 14:14 UTC, Kihyun92 commented on src/index.js
> +          }}
함수가 굉장히 복잡해보여요. 이 경우에는 핸들러 함수로 따로 분리하는게 좋을 것 같습니다~

그리고 정규식과 DOM객체에 접근하여 문제를 해결하셨네요. DOM객체 직접 접근하는 것은 우리에게 많은 일을 가능하도록 기능들을 제공하지만 그만큼 사용하기 어렵다는 단점이 있어요. 그리고 해당 값을 접근하는 방법이 어디서는 접근 가능하기 때문에 추적이 어려운 이유도 있고, 또 우리는 어떤 상태에 대해서 어떻게 보여줄지를 결정하고 싶은데 DOM은 그 반대에요. 지금은 DOM에서부터 상태를 얻고 상태를 다시 DOM에 반영하고 있죠.

우리는 특정한 상태를 가지고 있고 그 상태를 가지고 화면에 보여주도록 수정해보시면 좋을 것 같아요

2021-01-21 14:14 UTC, Kihyun92 commented on src/index.js
> +        ))} */}
이 부분은 왜 주석처리된 걸까요~?😁

2021-01-22 13:56 UTC, Kihyun92 commented
@minseongkimdev 님~ 커맨트 확인 부탁드립니다 🙏

혹시 어려운 점이나 의논이 필요하다면 편하게 말씀주세요~

2021-01-23 12:14 UTC, minseongkimdev commented on src/index.js
> +// eslint config에 직접 추가하는게 아니라 index.js 상단에 추가하는것이 좋다. 프로젝트 전역에 규칙이 적용되기 때문이다.
넵 다음부터 그렇게 하도록 하겠습니다 :)

2021-01-23 12:19 UTC, minseongkimdev commented on src/index.js
> +          }}
친절한 설명 감사드립니다! 제가 과제를 잘못 이해하고 접근을 했던것 같습니다.

DOM에 상태를 얻고 상태를 변경하고 다시 DOM을 바꾸는식의  쌍방이 아닌, 우리는 상태만 바꾸고 이에 따라 다시 그려야 한다. 라는 코치님의 설명이 리액트의 패러다임을 이해하는데 도움이 돼었습니다 ㅎㅎ

또한 해설 강의를 참고하니 "우리는 특정한 상태를 가지고 있고 그 상태를 가지고 화면에 보여주도록 수정해보시면 좋을 것 같아요" 라는 의미가 더 명확하게 이해된 것 같습니다. 

정확하게 짚어주셔서 감사드립니다 !! ㅎㅎ

2021-01-23 12:20 UTC, minseongkimdev commented on src/index.js
> +        ))} */}
엇.. 수정하여 PR 날리겠습니다. 감사합니다 ~

2021-01-23 12:21 UTC, minseongkimdev commented
커멘트 늦어서 죄송합니다 ㅠ PR다시 날리기 위해 close 하겠습니다!!

2021-01-23 12:21 UTC, closed without merging

2021-01-23 13:31 UTC, Kihyun92 commented
@minseongkimdev PR을 다시 생성하는 이유가 있나요? 

> Pull Request를 했지만 수정하고 싶을 때가 있습니다. 코드 리뷰 내용을 보고 반영하기 위해 고칠 때가 많은데, 해당 브랜치에 가서 Commit을 추가하고 Push만 하면 됩니다.

- https://github.com/CodeSoom/git-training#%EC%9E%91%EC%97%85-%EC%88%98%EC%A0%95%ED%95%98%EA%B8%B0