1주차 1번째 과제
CodeSoom/react-week1-assignment-1 pull request #89
Opened 2021-05-03 12:51 UTC by yujong-lee

eslint경고가 없고 모든 인수테스트가 통과함을 확인하였습니다.

그런데 eslint disable을 하나 더 추가해야 한다고 하셨는데 추가하지 않고도 오류가 뜨지 않았기에 맞게 한 것인지 좀 의심스럽습니다. ^^

지금 제출한 해법 외에는 클로저를 이용해 onClick함수만 count변수에 접근하도록 하는 방법을 처음에 떠올렸었는데, let를 여전히 사용해야해서 구현하지는 않았습니다. 최종적으로는 버튼을 누를 때 render를 다시 호출하도록 구현하였는데, 이것이 괜찮은 해법인지 궁금합니다.

2021-05-04 17:03 UTC, moonkii requested changes
![image](https://user-images.githubusercontent.com/46776329/117040889-56783800-ad45-11eb-8b75-35785a013205.png)

린트를 통과하고 과제 요구 조건을 모두 만족했으면 맞게 하신거에요 ;)
이번 과제의 목적은 `let` 을 제거하는 것이기 때문에 잘 해결하신 것 같아요. 👏👏 👏

2021-05-04 17:03 UTC, moonkii commented on src/index.js
> +        {[1, 2, 3].map((newCount) => (
`count` 와 이름이 겹쳐서 `newCount` 로 변수명을 하신걸까요?

더 의도를 드러낼 수 있는 이름을 사용하면 좋을 것 같아요!

2021-05-04 19:31 UTC, yujong-lee commented on src/index.js
> +        {[1, 2, 3].map((newCount) => (
다음 렌더링 때의 새로운 카운트라는 의미에서 지은 변수명이었어요. 
```javascript
onClick={() => render(count + 1)}
```
여기서는 `count + 1 - newCount`인 셈이죠.

제 의도를 좀 더 드러낸다면, 
```javascript
{[1, 2, 3].map((newCount) => (
          <button
            type="button"
            onClick={() => render(newCount)}
          >
            {newCount}
          </button>
        ))}
```
이 버튼의 목적은 count를 기존 값을 바탕으로 증가시키는 것이 아니라 아예 특정 값으로 정하는 것이니까 `setCount`같은 것이 좋을까요? 그런데 앞에 `set`을 붙이니까 숫자를 담는 변수명이라기 보다는 함수명에 더 가까워보이네요...

혹시 더 좋은 이름이 있을까요?

2021-05-05 15:43 UTC, moonkii commented on src/index.js
> +        {[1, 2, 3].map((newCount) => (
그런 의도를 가지고 변수명을 지으신거라면 괜찮은 것 같아요!

항상 '왜' 가 중요하니까요 ;)

2021-05-05 15:45 UTC, moonkii approved these changes
1주차 과제 1을 빠르게 잘 해내신것 같아요! 🎊 

1주차 과제를 모두 완료하시고 1주차 회고를 작성하신다음 슬랙의 주간회고 채널에 공유해주시면 merge 하도록 하겠습니다 😄

2021-05-10 14:34 UTC, merged