Remove let
CodeSoom/react-week1-assignment-1 pull request #94
Opened 2021-05-04 16:17 UTC by hanvit7

let을 사용하지 않기 위해 count 변수 선언을 const 배열로 변경
no-use-before-define을 피하기 위해 handleClick함수와
handleClickNumber 함수를 익명함수로 변경

안녕하세요 트레이너님 리뷰요청드립니다.

과제 설명에 통과를 위해서는 lint 룰을 1개 추가해야한다고 되어있는데
전 추가 없이 테스트는 통과가 되버렸네요...
아마 제가 과제의 의도를 제대로 파악하지 못한고 꼼수를 써서 그런거겠죠??
피드백 부탁드립니다. 감사합니다.

2021-05-05 15:17 UTC, Kihyun92 requested changes
안녕하세요 한빛님~ 첫 리뷰 드리네요 :) 

진행하시다가 의논이 필요한 부분이 있다면 PR에 커맨트도 좋고, 슬랙 리액트-4기 채널이나 DM으로 편하게 말씀해주세요~

render 함수 내에서 `no-use-before-define`을 피하기 위해 익명함수로 변경하신 것 같은데, 이 부분은 `use before define`을 통해 해결할 수는 없을까요?

진행하시다가 의논이 필요한 부분이 있다면 PR에 커맨트도 좋고, 슬랙 리액트-4기 채널이나 DM으로 편하게 말씀해주세요~

2021-05-05 15:17 UTC, Kihyun92 commented on src/index.js
> +  // console.log(tagName, props, ...children);
불필요한 콘솔 로그는 제거해주세요~

2021-05-05 15:17 UTC, Kihyun92 commented on src/index.js
> +const count = [0];
배열을 사용하여 문제를 해결해보셨군요 ㅎㅎ 좋습니다 :)

하지만 배열 내의 값을 변경할 수 있기 때문에 const로 선언하여 배열로 값을 관리한다고 해서 재할당이 불가능한 것은 아닙니다. 이 경우에 이 값은 언제 어디서 변하는지 예측하기 어렵겠죠. 객체도 마찬가지구요.

이번 과제의 의도를 조금 더 고민해보시면 좋을 것 같습니다 😊

2021-05-07 05:45 UTC, hanvit7 commented
안녕하세요 트레이너팀 리뷰요청드립니다.
역시 배열을 사용하는 방법을 잘못된 방법이였네요 ㅎㅎ
다시 생각해보면서 돔에 있는 p 태그 값을 가져오는 방법을 생각해봤는데
props를 이용해서 가능할 것 같아서 수정해보았습니다.

use before define은 아직 감을 못잡고 있습니다ㅠㅠ
힌트 좀 부탁드립니다. ㅎㅎ;;

2021-05-07 12:55 UTC, Kihyun92 commented on src/index.js
> +function render(count = 0) {
만약 인자가 여러개가 된다면 어떻게 처리할 수 있을지 고민해보셔도 좋을 것 같아요~

2021-05-07 14:07 UTC, hanvit7 commented
트레이너팀 리뷰요청드립니다.
handleClick, handleClickNumber 함수를 render 함수 내부에 선언 하여 오류 해결하였습니다.

왜... 각각 함수를 놔두고 문제를 해결해야 한다고 생각했을까요 ㅎㅎ

2021-05-07 15:13 UTC, Kihyun92 reviewed
문제 없이 lint를 통과했다면 굳이 추가하지 않아도 될 것 같아요 :)

2021-05-07 16:10 UTC, hanvit7 commented
트레이너님 말씀하신 부분 리펙토링 하였습니다. 리뷰요청드립니다.

2021-05-08 14:04 UTC, Kihyun92 requested changes

2021-05-08 14:04 UTC, Kihyun92 commented on src/index.js
> +  // const handleClickNumber = (value) => render(value);
예외처리는 가능하면 사용하지 않도록 리팩터링 하면 좋습니다.

이 경우에는 핸들러 함수를 사용하는 쪽에서 render할 값을 계산해서 넘기는 방식을 통해 예외처리를 제거할 수 있을 것 같아요~

그리고 불필요한 주석은 제거해주세요!

2021-05-09 14:14 UTC, hanvit7 commented
불필요한 매개 변수를 제거하여 리팩토링 하였습니다.

첫주는 휴일과 허리아픔 등의 변명으로 제대로 못한것 같네요 ㅎ
다음주엔 더 많은 리뷰요청 드릴수있도록 노력하겠습니다.

2021-05-09 14:24 UTC, Kihyun92 approved these changes
고생하셨습니다 :) 이번 과제는 어프루브 하도록 하겠습니다.

과제 풀이 영상을 꼭 보시고, 아샬님은 어떻게 문제를 풀어나가는지 풀이과정을 눈여겨 보시면 좋을 것 같습니다.

슬랙 채널에 회고 남겨주시면 머지하겠습니다 :)

2021-05-10 14:01 UTC, merged