Remove let
CodeSoom/react-week1-assignment-1 pull request #99
Opened 2021-05-07 11:44 UTC by dngwoodo

안녕하세요 트레이너님
인생 첫 리뷰 요청인것 같습니다. 너무 늦어 죄송합니다.

2021-05-07 13:28 UTC, Kihyun92 requested changes
안녕하세요~~ 
첫리뷰 축하드립니다 😁  앞으로도 넘 부담갖지 마시고 PR은 최대한 빠르게 보내주세요~!

과제의 의도를 잘 파악해주신 것 같아요 👍🏼  
간단하게 파라미터를 사용해서 상태를 관리하면 함수내에서 상태를 불변하게 유지할 수 있게 됩니다. 이 경우 또 어떤 장점이 있을지 생각해보셔도 좋을 것 같네요ㅎㅎ

그리고 동료들과 함께 관리하는 코드이기 때문에 주석보다는 가능하면 커밋 메시지에 왜, 무엇을 위한 작업인지를 남겨주시는게 좋을 것 같습니다 ㅎㅎ

특히 학습을 위한 주석이라면 더 사용하지 않고, 본인의 것으로 만드는게 좋을 것 같습니다. 주석에 의존하게 될 것 같아요.

항상 코드 자체에 본인의 의도를 드러내려고 고민해보시면 좋을 것 같습니다😊

2021-05-07 13:38 UTC, Kihyun92 commented on src/index.js
> +        {[1, 2, 3].map((i) => (<p>{i}</p>))}
이 부분도 버튼으로 구현되어야하지 않나요~?

2021-05-07 16:14 UTC, dngwoodo commented on src/index.js
> +  const count = state;
감사합니다. 수정했습니다!

2021-05-07 16:21 UTC, dngwoodo commented
> 안녕하세요~~
> 첫리뷰 축하드립니다 😁 앞으로도 넘 부담갖지 마시고 PR은 최대한 빠르게 보내주세요~!
> 
> 과제의 의도를 잘 파악해주신 것 같아요 👍🏼
> 간단하게 파라미터를 사용해서 상태를 관리하면 함수내에서 상태를 불변하게 유지할 수 있게 됩니다. 이 경우 또 어떤 장점이 있을지 생각해보셔도 좋을 것 같네요ㅎㅎ
> 
> 그리고 동료들과 함께 관리하는 코드이기 때문에 주석보다는 가능하면 커밋 메시지에 왜, 무엇을 위한 작업인지를 남겨주시는게 좋을 것 같습니다 ㅎㅎ
> 
> 특히 학습을 위한 주석이라면 더 사용하지 않고, 본인의 것으로 만드는게 좋을 것 같습니다. 주석에 의존하게 될 것 같아요.
> 
> 항상 코드 자체에 본인의 의도를 드러내려고 고민해보시면 좋을 것 같습니다😊

좋은 리뷰 감사합니다. 제가 회사에서도 1인 개발자다보니 협업을 하지 못하고 있어서 이런 부분이 많이 부족한 것 같습니다. 그리고 항상 고민하는 부분이 커밋 제목 부분을 어떻게 적어야 되는지에 대한 것입니다. 제목에서 이 커밋의 어느정도를 드러내야 되는지에 대한 것인데  이 부분에 대해서도 조금 알려주시면 감사하겠습니다!

2021-05-08 13:25 UTC, Kihyun92 reviewed
과제를 잘 진행해주셨네요 👍🏼  두번째 과제도 기다리고 있겠습니다 :)

깃 커밋 메시지 관련해서는 아래 문서 참고해보시면 좋을 것 같아요~

참고: 
- https://github.com/ikaruce/git-style-guide#messages-%EB%A9%94%EC%8B%9C%EC%A7%80

2021-05-08 13:25 UTC, Kihyun92 commented on .eslintrc.js
> +  rules: {},
eslint warning 을 제거하기 위해서 추가하신 것 같아요.

잘 해결해 주셨지만, 저희는 현재 이 프로젝트 내에서 리액트를 사용하고 있지 않기도 하고, 이 경우엔 프로젝트 전반적으로 해당 세팅이 적용되기 때문에 다른곳에서 발생하는 문제를 발견하지 못할 수도 있을 것 같아요.

일단은 문제가 되는 부분에만 룰을 추가해주는건 어떨까요? 😊

2021-05-08 13:25 UTC, Kihyun92 commented on src/index.js
> +const render = (state = 0) => {
`state`라는 용어는 많은 의미를 담고 있는 것 같아요. 조금 더 명확하게 역할을 드러내 줘도 좋을 것 같군요 ㅎㅎ

2021-05-08 16:04 UTC, dngwoodo commented on .eslintrc.js
> +  rules: {},
settings 부분을 지우게 되면 해당 경고가 뜨고
Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.

react 부분의 eslint(eslint-config-airbnb, eslint-plugin-react)를 eslintre.js에서 삭제하고 실행시켜보니 index.js가 아닌 다른 파일에서 오류가 생겨서 우선 수정을 하진 않았습니다.

그리고 별개로 질문이 있는데 eslint-plugin-react을 커스텀하게 쓰는게 아닌 recommended를 사용하고 이씩 때문에 plugins: ['react'] 이 부분은 빼줘도 상관없을까요 ?

2021-05-08 16:04 UTC, dngwoodo commented on src/index.js
> +const render = (state = 0) => {
감사합니다 변경했습니다!

2021-05-08 16:07 UTC, dngwoodo commented on src/index.js
> +const render = (state = 0) => {
이번주는 조금 사정이 있어 과제2를 늦게하게 되었는데 해당 주차가 지나면 리퀘스트를 보낼 수 없으니 우선 강의와 다른분들 풀리퀘를 보고 고쳐서 해보겠습니다. 다음주부터는 과제 전부 참여해보겠습니다!

2021-05-09 13:16 UTC, Kihyun92 commented on .eslintrc.js
> +  rules: {},
아앗 이 부분은 제가 착각했네요.😅  혼동을 드려 죄송합니다.

그리고 질문주신 부분은 말씀하신대로 react recommended preset을 사용하기 때문에 plugins 에 설정한 부분은 없어도 될 것 같아요.
좀더 확인해봐야겠네요 👍🏼

2021-05-09 13:19 UTC, Kihyun92 approved these changes
이번 과제의 의도를 잘 파악하신 것 같네요~ 👍🏼 

과제 풀이 영상을 꼭 보시고 아샬님은 어떻게 접근하는지 확인해보시면 좋을 것 같습니다 :)

슬랙의 주간회고 채널에 회고 꼭 남겨주세요~

2021-08-08 07:45 UTC, merged